# Application
spring.application.name=greenhouse-app
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/greenhouse_db
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# OAuth2 Gmail
spring.security.oauth2.client.registration.google.client-id=633682661067-n4popcn9qcbtsmo2vj23eoqu3shqj5f7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Frontend base URL — OAuth2 success handler redirects here after login
app.frontend.base-url=http://localhost:5173

# Springdoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logging
logging.level.com.greenhouse=INFO
logging.level.org.springframework.security=WARN
